import FeedbackForm from '../../components/FeedbackForm/FeedbackForm'
import Head from 'next/head'

const Feedback: React.FC<{}> = () => {
    return <>
        <Head>
            <title>FITNESS INSIGHTS | Feedback</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <FeedbackForm />
        </div>
    </>
}

export default Feedback