import Head from 'next/head'
import { homePageData } from '@/utils'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { SlArrowRight } from 'react-icons/sl'

const Home: React.FC<{}> = () => {

  const { section_main, section_three_cards, section_auxillary, section_closing } = homePageData

  return (
    <>
      <Head>
        <title>FITNESS INSIGHTS | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.body}>

        <section className={styles.section_main}>
          <div className={styles.main_heads}>
            <h1 className={styles.main_h1}>{section_main.heading}</h1>
            <h3 className={styles.main_h3}>{section_main.sub}</h3>
          </div>
        </section>

        <section className={styles.section_three_cards}>
          {section_three_cards.map((para, index) => <div className={styles.card} key={index}>
            <p className={styles.card_p}>{para}</p>
          </div>)}
        </section>

        <section className={styles.section_auxillary}>
          <div className={styles.aux_heads}>
            <h1 className={styles.aux_h1}>{section_auxillary.heading}</h1>
            <h3 className={styles.aux_h3}>{section_auxillary.sub}</h3>
          </div>
        </section>

        <section className={styles.section_closing}>
          <div className={styles.close_heads}>
            <h1 className={styles.close_h1}>{section_closing.heading}</h1>
            <h3 className={styles.close_h3}>{section_closing.sub}</h3>
            <Link href="/explore" className={styles.section_close_button_link}>
              <button className={styles.section_close_button}>
                <p className={styles.button_text}>Explore</p>
                <SlArrowRight />
              </button>
            </Link>
          </div>
        </section>

        <section className={styles.disclaimer}>
          <p className={styles.disclaimer_text}></p>
        </section>

      </div>

    </>
  )
}

export default Home