// IMPORTS 

import Head from "next/head"

//import components
import ExploreCard from "../../../components/ExploreCard/ExploreCard"

//import utils data 
import { fatLossExploreCard, miscellaneousExploreCard, muscleBuildingExploreCard } from "@/utils"

// import image paths as StaticImageData
import ExploreMuscBg from '../../../public/Images/Explore-musc-bg.jpg'
import ExploreFatBg from '../../../public/Images/Explore-fat-bg.jpg'
import ExploreMiscBg from '../../../public/Images/Explore-misc-bg.jpg'

// import stylesheet
import styles from '../../styles/Explore.module.css'


// Page 
const Explore: React.FC<{}> = () => {

  return <>
    <Head>
        <title>FITNESS INSIGHTS | Explore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    
    <div className={styles.explore_card_container}>
      <ExploreCard {...muscleBuildingExploreCard} img_path={ExploreMuscBg}/>
      <ExploreCard {...fatLossExploreCard} img_path={ExploreFatBg}/>
      <ExploreCard {...miscellaneousExploreCard} img_path={ExploreMiscBg}/>
    </div>
  </>
}

export default Explore